/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SupportImport } from './routes/support'
import { Route as SettingsImport } from './routes/settings'
import { Route as ProfileImport } from './routes/profile'
import { Route as MoreImport } from './routes/more'
import { Route as ManageImport } from './routes/manage'
import { Route as BalanceImport } from './routes/balance'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SupportRoute = SupportImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRoute,
} as any)

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const MoreRoute = MoreImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRoute,
} as any)

const ManageRoute = ManageImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRoute,
} as any)

const BalanceRoute = BalanceImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/balance': {
      id: '/balance'
      path: '/balance'
      fullPath: '/balance'
      preLoaderRoute: typeof BalanceImport
      parentRoute: typeof rootRoute
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageImport
      parentRoute: typeof rootRoute
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/balance': typeof BalanceRoute
  '/manage': typeof ManageRoute
  '/more': typeof MoreRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/balance': typeof BalanceRoute
  '/manage': typeof ManageRoute
  '/more': typeof MoreRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/balance': typeof BalanceRoute
  '/manage': typeof ManageRoute
  '/more': typeof MoreRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/balance'
    | '/manage'
    | '/more'
    | '/profile'
    | '/settings'
    | '/support'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/balance'
    | '/manage'
    | '/more'
    | '/profile'
    | '/settings'
    | '/support'
  id:
    | '__root__'
    | '/'
    | '/balance'
    | '/manage'
    | '/more'
    | '/profile'
    | '/settings'
    | '/support'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BalanceRoute: typeof BalanceRoute
  ManageRoute: typeof ManageRoute
  MoreRoute: typeof MoreRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BalanceRoute: BalanceRoute,
  ManageRoute: ManageRoute,
  MoreRoute: MoreRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/balance",
        "/manage",
        "/more",
        "/profile",
        "/settings",
        "/support"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/balance": {
      "filePath": "balance.tsx"
    },
    "/manage": {
      "filePath": "manage.tsx"
    },
    "/more": {
      "filePath": "more.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/support": {
      "filePath": "support.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
